### ISSUE TITLE
[doc] Write data import overview page

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ConnectionsBundle#100]
Page should be written, that has image of the whole import process + sync. It should include description of each stage briefly with command examples (maybe use sphinx import functionality to deduplicate code).

Possibly, Magento can be used as an example. Magento page itself will have only usage instructions. This page will be more in depth.

Further discussions are needed.

**Comment by mindaugasbarysas** [comment]
Does this suffice? https://github.com/ongr-io/ConnectionsBundle/pull/140 + current state of ConnectionsBundle documentation? I suppose not...
