### ISSUE TITLE
Not required param shop-id for ongr:sync:storage:create

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/ConnectionsBundle#116]
`ongr:sync:storage:create` asks for shop id but there are configuration available for all present shops
and tables for all shops should be present for `ongr:sync:provide` command.

So i suggest removing `--shop-id=...` and make command to create tables for all shops.

**Comment by trylika** [comment]
`--shop-id=...` is optional, so there is no issue in here, also might be related to #102

**Comment by gyKa** [comment]
Is this issue still relevant?

**Comment by GrandLTU** [comment]
I believe yes, when sync storage is used storages for all configured shops are required.
Maybe make that when no `--shop-id=...` is provided command creates storages for all configured shops.

**Comment by tautrimas** [comment]
I agree with @GrandLTU. All storages should be configured if no `--shop-id` is used.

**Comment by tautrimas** [comment]
After consulting with @GrandLTU, suggestion is to

1. validate `--shop-id` so that it is a valid shop id.
2. if value is not given, first shop id should be used (in case it is non-multi-shop).
