### ISSUE TITLE
Pipeline context is not updated after pipeline iteration.

### ISSUE THREAD

**Issue by mindaugasbarysas** [ongr-io/ConnectionsBundle#123]
Pipeline context is set here:
https://github.com/ongr-io/ConnectionsBundle/blob/master/Pipeline/Pipeline.php#L70, but it is never updated, so each item gets the same context.

**Comment by GrandLTU** [comment]
I don't really see where is the problem.

**Comment by mindaugasbarysas** [comment]
You might need to bring data from consume event listener to finish event listener. Currently there is no way to do so. Example situation: you want to see how many items there are to be persisted to Elasticsearch, to see whether you need to call `commit()`, which fails if there are no documents persisted.

**Comment by GrandLTU** [comment]
If context is an object same object between all events will be shared.

**Comment by mindaugasbarysas** [comment]
Unfortunately that is not the case. @gimikus, please comment in more detail.

**Comment by gimikus** [comment]
Yes @mindaugasbarysas  you are right. Every context lives only one iteration and is not saved after iteration.

**Comment by GrandLTU** [comment]
That is the case when context is an array for example. I would suggest creating some AbstractContext class and making pipeline to use it.
