### ISSUE TITLE
Entity\SyncJobs should be removed

### ISSUE THREAD

**Issue by trylika** [ongr-io/ConnectionsBundle#128]
It appears that the whole Enityt\SyncJobs class is not used, except for static constants.
This should be re-factored, and useless entity removed.

`https://github.com/ongr-io/ConnectionsBundle/blob/master/Entity/SyncJob.php`

**Comment by gyKa** [comment]
`Sync\DiffProvider\SyncJobs\JobManager` uses it.

**Comment by trylika** [comment]
@gyKa yes it is, but jobmanager will be removed in #115, since it's not used, thus making this class absolutelly useless.

**Comment by gyKa** [comment]
:+1: :wink:
