### ISSUE TITLE
What is the purpose of DiffImport class?

### ISSUE THREAD

**Issue by mindaugasbarysas** [ongr-io/ConnectionsBundle#133]
See: https://github.com/ongr-io/ConnectionsBundle/blob/master/Sync/DiffImport/DiffImport.php

I can't find anything using it. What is its' purpose? Maybe it can be removed?

**Comment by trylika** [comment]
It seams it's not used, can you remove it?

**Comment by mindaugasbarysas** [comment]
Will do
