### ISSUE TITLE
AbstractImportModifyEventListener should log ERROR

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ConnectionsBundle#160]
Should [AbstractImportModifyEventListener.php#L48](https://github.com/ongr-io/ConnectionsBundle/blob/5e228f247a80e219740a6e031e340cebad5c52eb/EventListener/AbstractImportModifyEventListener.php#L48) log NOTICE or ERROR? This is an error and action should be taken to fix such inconsistencies. @saimaz, @mindaugasbarysas?

**Comment by mindaugasbarysas** [comment]
I aggree completely with @tautrimas. This should be an error.

**Comment by tautrimas** [comment]
- [ ] Please check that there are no more `NOTICE` logging in such situations in other places in Connections.

**Comment by saimaz** [comment]
Yes, this definitely must be an error.
