### ISSUE TITLE
Doctrine documentation advises against quoting identifiers

### ISSUE THREAD

**Issue by mindaugasbarysas** [ongr-io/ConnectionsBundle#83]
code in question:

https://github.com/ongr-io/ConnectionsBundle/blob/63948a849c8befb4ddeeb4981da43438e456021a/Sync/StorageManager/MysqlStorageManager.php#L110

https://github.com/ongr-io/ConnectionsBundle/blob/63948a849c8befb4ddeeb4981da43438e456021a/Sync/StorageManager/MysqlStorageManager.php#L212

related discussion:

https://github.com/ongr-io/ConnectionsBundle/pull/81/files#r22380117

**Comment by tautrimas** [comment]
No more dynamically quoted statements seems left
