### ISSUE TITLE
No way to configure shop id for sync storage.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/ConnectionsBundle#88]
There is no way to configure shop id for command `ongr:sync:provide magento`  
while `ongr:sync:execute magento.product` requires shop id.
So `provide` puts data into `ongr_sync_storage` but `execute` expects data in `ongr_sync_storage_{shop_id}` .

**Comment by GrandLTU** [comment]
After more inspection `DoctrineExtractor` and `PassthroughExtractor` does not provide shop id for storage->save

**Comment by MindaugasR** [comment]
Found requirements to solve this solution:
- [ ] Implement shop ids getting from configuration, and passing it to SyncStorageFacility.
- [ ] Design item skip pattern in Pipeline #53, to allow skiping items from wrong shops.
