### ISSUE TITLE
SQL relations required?

### ISSUE THREAD

**Issue by trylika** [ongr-io/ConnectionsBundle#93]
When no sql relations defined in connector, ConnectionsBundle fails, because it expects at least one relation. Should relations be required?

example relation:
https://github.com/ongr-io/MagentoConnectorBundle/blob/master/Resources/config/services.yml#L7

**Comment by tautrimas** [comment]
Does it still fail?

**Comment by trylika** [comment]
i'm not shure yet, maybe this was fixed in newest version of connectionsbundle, we'll find out soon when writing sync test in oxid connector.

**Comment by trylika** [comment]
we tested this, with newest release of ConnectionsBundle even if there are no relations, errors are not thrown. closing this issue.
